name: dev CI/CD pipeline
on:
  push: { branches: main }



jobs:
  deploy-preprod:
    name: Deploy to pre-prod environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Imprimir lista de archivos
      run: ls -R

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1 
      with:
        name: MyStack
        template: lab-network.yaml
